:listing:
  :mls_num: "ListingID"
  :price:   "ListPrice"
  :beds:    "Bedrooms"
  :year:    "Age"
  :mls_data_updated_at:   "PhotoModificationTimestamp"
  :mls_photo_updated_at:  "ModificationTimestamp"

  :modify:
    - rets_sqft
    - rets_baths
    - rets_active

  :address_fields:
    - "StreetNumber"
    - "StreetName"
    - "City"
    - "StateOrProvince"
    - "PostalCode"

  :extra:
    - "ListPrice"
    - "Bedrooms"
    - "BathsTotal"
    - "HalfBaths"
    - "Age"
    - "SqFtRange"
    - "PublicRemarks"
    - "Acreage"
    - "County"
    - "Style"
    - "Condition"
    - "Includes"
    - "Appliance"
    - "Fireplace"
    - "InteriorFeatures"
    - "DiningRoom"
    - "Misc"
    - "Garage"
    - "PropertyConstructionMaterial"
    - "SiteDescription"
    - "Miscellaneous"
    - "TypeHeat"
    - "Gas"
    - "Electric"
    - "Sewer"
    - "Water"
    - "Floors"
    - "LotNumber"
    - "Possession"
    - "ContingencyStatus"
    - "Zoning"
    - "Units"
    - "OccupancyDescription"
    - "ListingID"

  :premium:
    - "ListDate"
    - "AddressSubdivisionName"
    - "Area"
    - "ProposedAssessments"
    - "ConfirmedSpcAssessment"
    - "Foreclosure"
    - "ShortSaleYN"
    - "DueDiligencePeriod"
    - "ElementarySchool"
    - "MiddleSchool"
    - "HighSchool"
    - "VirtualTourURL"
    - "WoodedAcres"
    - "TaxID"
    - "DeedBookNumber"
    - "DeedPage"
    - "PlatBook"
    - "PlatBookPage"
    - "ClosePrice"
    - "CloseDate"
    - "OwnerName"
    - "HomeWarrantyYN"

  :exclude:
    - "ListingStatus"
    - "DaysOnMarketContinuous"
    - "IDX"
    - "PropertyType"
    - "OfficeIDX"
    - "DisplayAddressListing"
    - "PhotoCount"
    - "PhotoModificationTimestamp"
    - "ModificationTimestamp"
    - "VirtualTourYN"
    - "ListingBoardID"
    - "ListingFirmID"
    - "ListingOfficeID"
    - "ListingOfficeUID"
    - "ListingAgentID"
    - "ListingAgentUID"
    - "ListOfficeAffiliation"
    - "OfficeStatus"
    - "AgentStatus"
    - "AgentIDX"
    - "BuyerBrokerFee"
    - "DateChange"
    - "DisplayFlagListing"
    - "Rooms"
    - "HomeWarrantyAmount"
    - "BlogYN"
    - "PrivateRemarks"
    - "RentFee"
    - "FinancialTerms"
